import {
  AlertCircle,
  Bold,
  Check,
  ChevronDown,
  ChevronRight,
  Cloud,
  File,
  FileCode,
  FileIcon,
  FileText,
  Folder,
  FolderOpen,
  Heading1,
  Heading2,
  Heading3,
  ImageIcon,
  Italic,
  LinkIcon,
  List,
  ListOrdered,
  Menu,
  Moon,
  MoreHorizontal,
  MoreVertical,
  PanelLeft,
  Plus,
  Quote,
  Command,
  Save,
  Search,
  Settings,
  Share,
  Strikethrough,
  Sun,
  Type,
  X,
} from "lucide-react";

export const Icons = {
  alertCircle: AlertCircle,
  bold: Bold,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  cloud: Cloud,
  file: File,
  fileCode: FileCode,
  fileText: FileText,
  folder: Folder,
  folderOpen: FolderOpen,
  h1: Heading1,
  h2: Heading2,
  h3: Heading3,
  image: ImageIcon,
  italic: Italic,
  link: LinkIcon,
  list: List,
  listOrdered: ListOrdered,
  menu: Menu,
  moon: Moon,
  moreHorizontal: MoreHorizontal,
  moreVertical: MoreVertical,
  panelLeft: PanelLeft,
  plus: Plus,
  quote: Quote,
  command: Command,
  save: Save,
  search: Search,
  settings: Settings,
  share: Share,
  strikethrough: Strikethrough,
  sun: Sun,
  type: Type,
  unknown: FileIcon,
  x: X,
};
